# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1121, 840)
        self.AddButton = QtWidgets.QPushButton(Dialog)
        self.AddButton.setGeometry(QtCore.QRect(660, 750, 421, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AddButton.setFont(font)
        self.AddButton.setObjectName("AddButton")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(40, 20, 1041, 641))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(50, 60, 191, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(140, 190, 91, 31))
        self.label_2.setObjectName("label_2")
        self.Car = QtWidgets.QLineEdit(self.groupBox)
        self.Car.setGeometry(QtCore.QRect(250, 190, 261, 31))
        self.Car.setObjectName("Car")
        self.PhoneNumber = QtWidgets.QLineEdit(self.groupBox)
        self.PhoneNumber.setGeometry(QtCore.QRect(250, 70, 261, 31))
        self.PhoneNumber.setObjectName("PhoneNumber")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(180, 120, 71, 41))
        self.label_3.setObjectName("label_3")
        self.Name = QtWidgets.QLineEdit(self.groupBox)
        self.Name.setGeometry(QtCore.QRect(250, 130, 261, 31))
        self.Name.setObjectName("Name")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(110, 250, 121, 31))
        self.label_4.setObjectName("label_4")
        self.Cast = QtWidgets.QLineEdit(self.groupBox)
        self.Cast.setGeometry(QtCore.QRect(250, 250, 261, 31))
        self.Cast.setObjectName("Cast")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(160, 310, 71, 31))
        self.label_5.setObjectName("label_5")
        self.Time = QtWidgets.QLineEdit(self.groupBox)
        self.Time.setGeometry(QtCore.QRect(250, 310, 261, 31))
        self.Time.setObjectName("Time")
        self.BackButton = QtWidgets.QPushButton(Dialog)
        self.BackButton.setGeometry(QtCore.QRect(40, 750, 421, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.BackButton.setFont(font)
        self.BackButton.setObjectName("BackButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.AddButton.setText(_translate("Dialog", "Добавить"))
        self.groupBox.setTitle(_translate("Dialog", "Информация"))
        self.label.setText(_translate("Dialog", "Номер телефона:"))
        self.label_2.setText(_translate("Dialog", "Машина:"))
        self.label_3.setText(_translate("Dialog", "ФИО:"))
        self.label_4.setText(_translate("Dialog", "Стоимость:"))
        self.label_5.setText(_translate("Dialog", "Время:"))
        self.BackButton.setText(_translate("Dialog", "Добавить"))
