# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Find.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1179, 838)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 9, 1141, 271))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.FindButton = QtWidgets.QPushButton(self.groupBox)
        self.FindButton.setGeometry(QtCore.QRect(960, 210, 171, 51))
        self.FindButton.setObjectName("FindButton")
        self.Number = QtWidgets.QLineEdit(self.groupBox)
        self.Number.setGeometry(QtCore.QRect(150, 40, 181, 31))
        self.Number.setObjectName("Number")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(60, 40, 81, 31))
        self.label.setObjectName("label")
        self.FIO = QtWidgets.QLineEdit(self.groupBox)
        self.FIO.setGeometry(QtCore.QRect(150, 100, 271, 31))
        self.FIO.setObjectName("FIO")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(80, 100, 61, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 160, 101, 31))
        self.label_3.setObjectName("label_3")
        self.Car = QtWidgets.QLineEdit(self.groupBox)
        self.Car.setGeometry(QtCore.QRect(150, 160, 271, 31))
        self.Car.setObjectName("Car")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(150, 220, 271, 31))
        self.comboBox.setObjectName("comboBox")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox)
        self.calendarWidget.setGeometry(QtCore.QRect(450, 10, 481, 251))
        self.calendarWidget.setObjectName("calendarWidget")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(50, 220, 91, 31))
        self.label_4.setObjectName("label_4")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(990, 100, 231, 31))
        self.radioButton.setObjectName("radioButton")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 330, 1141, 491))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "GroupBox"))
        self.FindButton.setText(_translate("Dialog", "Найти"))
        self.label.setText(_translate("Dialog", "Номер:"))
        self.label_2.setText(_translate("Dialog", "ФИО:"))
        self.label_3.setText(_translate("Dialog", "Машина:"))
        self.label_4.setText(_translate("Dialog", "Работа:"))
        self.radioButton.setText(_translate("Dialog", "Дата?"))
