# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1113, 833)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 391, 811))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.Form = QtWidgets.QPushButton(self.groupBox)
        self.Form.setGeometry(QtCore.QRect(80, 690, 191, 61))
        self.Form.setObjectName("Form")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 151, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 339, 151, 31))
        self.label_2.setObjectName("label_2")
        self.Start = QtWidgets.QCalendarWidget(self.groupBox)
        self.Start.setGeometry(QtCore.QRect(0, 80, 392, 236))
        self.Start.setObjectName("Start")
        self.End = QtWidgets.QCalendarWidget(self.groupBox)
        self.End.setGeometry(QtCore.QRect(0, 380, 392, 236))
        self.End.setObjectName("End")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(420, 20, 681, 801))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Сформировать отчет"))
        self.Form.setText(_translate("Dialog", "Сформировать"))
        self.label.setText(_translate("Dialog", "Начало срока:"))
        self.label_2.setText(_translate("Dialog", "Конец срока:"))
