# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Works.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1118, 828)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(30, 20, 471, 791))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(560, 20, 541, 231))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 70, 211, 41))
        self.label.setObjectName("label")
        self.AddLine = QtWidgets.QLineEdit(self.groupBox)
        self.AddLine.setGeometry(QtCore.QRect(250, 71, 271, 31))
        self.AddLine.setObjectName("AddLine")
        self.AddButton = QtWidgets.QPushButton(self.groupBox)
        self.AddButton.setGeometry(QtCore.QRect(340, 170, 181, 41))
        self.AddButton.setObjectName("AddButton")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(560, 290, 541, 231))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 211, 41))
        self.label_2.setObjectName("label_2")
        self.DelLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.DelLine.setGeometry(QtCore.QRect(250, 71, 271, 31))
        self.DelLine.setObjectName("DelLine")
        self.DelButton = QtWidgets.QPushButton(self.groupBox_2)
        self.DelButton.setGeometry(QtCore.QRect(340, 170, 181, 41))
        self.DelButton.setObjectName("DelButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Добавить новый вид работ"))
        self.label.setText(_translate("Dialog", "Введите название:"))
        self.AddButton.setText(_translate("Dialog", "Добавить"))
        self.groupBox_2.setTitle(_translate("Dialog", "Удалить вид работ"))
        self.label_2.setText(_translate("Dialog", "Введите название:"))
        self.DelButton.setText(_translate("Dialog", "Удалить"))
